---
title: "Adverse_outcome"
author: "Ankur Shrivastava"
date: "6 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bl1, echo=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(sqldf)
library(tidyr)

anm_visit <- read.csv("anm_visit_detail.csv", stringsAsFactors = FALSE, header = TRUE,
                      na.strings=c("NULL","NULL "," NULL ","NA"," ","", "-1"))
str(anm_visit)
summary(anm_visit)

# The following variables represent categories and not character or integers.
# Hence they need to be converted to categories
categorical <- c("anm_visit_detail_breathlessness", "anm_visit_detail_urine",
                 "anm_visit_detail_abdomen_pain", "anm_visit_detail_edema",
                 "anm_visit_detail_body_edema", "anm_visit_detail_headache")

#Converting to categorical variables

anm_visit[, categorical] <- lapply(anm_visit[, categorical], as.factor)
str(anm_visit[, categorical])

#Following are date variables and should be changed to date
anm_visit$anm_visit_detail_followup_date <- ymd(anm_visit$anm_visit_detail_followup_date)

#Following are datetime variables and should be changed to datetime
datetimevars <- c("anm_visit_detail_form_start_time", "anm_visit_detail_form_fill_time",
                  "anm_visit_detail_receive_time")

anm_visit[, datetimevars] <- lapply(anm_visit[, datetimevars], ymd_hms)
str(anm_visit[, datetimevars])

#Following are numeric variables and should be changed to numeric
numvars <- c("anm_visit_detail_temp", "anm_visit_detail_gps_lat", "anm_visit_detail_gps_long")

anm_visit[, numvars] <- lapply(anm_visit[, numvars], as.numeric)
str(anm_visit[, numvars])

anm_visit$risk_status <- as.factor(anm_visit$risk_status)

levels(anm_visit$risk_status) <- c("Normal", "Risk", "High Risk")

```
```{r bl2, echo=TRUE}
pw_case_flag <- read.csv("pw_case_flag.csv", stringsAsFactors = FALSE, header = TRUE,
                         na.strings=c("NULL","NULL "," NULL ","NA"," ","", "-1"))

str(pw_case_flag)
summary(pw_case_flag)

#Following are date variables and should be changed to date
pw_case_flag$anm_visit_detail_followup_date <- ymd(pw_case_flag$anm_visit_detail_followup_date)
pw_case_flag$doc_visit_detail_followup_date <- ymd(pw_case_flag$doc_visit_detail_followup_date)

#Following are datetime variables and should be changed to datetime
datetimevars <- c("pw_case_flag_set_time", "doc_visit_detail_last_visit_date")

pw_case_flag[, datetimevars] <- lapply(pw_case_flag[, datetimevars], ymd_hms)
str(pw_case_flag[, datetimevars])

length(unique(pw_case_flag$pw_profile_id))
#There are 43783 unique pw ids 

pw_case_close <- read.csv("pw_case_close.csv", stringsAsFactors = FALSE, header = TRUE,
                     na.strings=c("NULL","NULL "," NULL ","NA"," ","", "-1"))
str(pw_case_close)
summary(pw_case_close)

# The following variables represent categories and not character or integers.
# Hence they need to be converted to categories
categorical <- c("pw_case_close_preg_outcome", "pw_case_close_delivery_outcome",
                 "pw_case_close_delivery_place", "pw_case_close_mother_status",
                 "pw_case_close_child_sex", "pw_case_close_delivery_type",
                 "pw_case_close_delivery_assistant")

#Converting to categorical variables
pw_case_close[, categorical] <- lapply(pw_case_close[, categorical], as.factor)
str(pw_case_close[, categorical])

#Following are date variables and should be changed to date
pw_case_close$pw_case_close_outcome_date <- ymd(pw_case_close$pw_case_close_outcome_date)

#Following are datetime variables and should be changed to datetime
datetimevars <- c("pw_case_close_date", "pw_case_close_receive_time")

pw_case_close[, datetimevars] <- lapply(pw_case_close[, datetimevars], ymd_hms)
str(pw_case_close[, datetimevars])

adverse_cases <- sqldf("select * from pw_case_close where pw_case_close_preg_outcome = 2 or 
                       pw_case_close_delivery_outcome in (2,3)")

levels(adverse_cases$pw_case_close_delivery_outcome) <- c("NA", "ALIVE", "NND", "SB")

length(unique(adverse_cases$pw_profile_id))
#There are 714 adverse cases

#Get all closed cases from pw_case_flag
closed_cases <- sqldf("select * from pw_case_flag where pw_case_flag_closed = 1")

```
```{r bl3,echo=TRUE}
#anm first registration records
anm_first_reg <- sqldf("select * from anm_visit where first_record = 1")

#Get registration risk and last risk status for adverse cases
adverse_cases_complete <- adverse_cases %>% left_join(anm_first_reg, by = "pw_profile_id")
adverse_cases_complete <- adverse_cases_complete %>% left_join(closed_cases, by = "pw_profile_id")

str(adverse_cases_complete)

adverse_cases_complete$pw_case_flag_risk_status <- as.factor(adverse_cases_complete$pw_case_flag_risk_status)

levels(adverse_cases_complete$pw_case_flag_risk_status) <- c("Normal", "Risk", "High Risk")

#filter by pregnancy outcome
aborted_cases <- adverse_cases_complete %>% filter(pw_case_close_preg_outcome == 2)

length(unique(aborted_cases$pw_profile_id))
#There are 488 aborted cases

#Initial risk status of aborted cases
agg_aborted_first_reg <- aborted_cases %>% group_by(risk_status) %>%
                         summarise(N = n())

gg <- ggplot(agg_aborted_first_reg, aes(x = risk_status, y = N, fill = risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  xlab("Risk Status") + ylab("Number of records") +
  ggtitle(("Aborted cases break up by Risk at First Registration"))

print(gg)

#Print the data
aborted_inital_risk = data.frame(Risk_Status = agg_aborted_first_reg$risk_status, No_of_records =  agg_aborted_first_reg$N)
print(aborted_inital_risk)

#Count the number of various risk cases at last risk status
agg_aborted_last_risk <- aborted_cases %>% group_by(pw_case_flag_risk_status) %>%
                         summarise(N = n()) 

gg <- ggplot(agg_aborted_last_risk, aes(x = pw_case_flag_risk_status, y = N, fill = pw_case_flag_risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  xlab("Risk Status") + ylab("Number of records") +
  ggtitle(("Aborted cases break up by Last Risk Status"))

print(gg)

#Print the data
aborted_last_risk = data.frame(Risk_Status = agg_aborted_last_risk$pw_case_flag_risk_status, No_of_records =  agg_aborted_last_risk$N)
print(aborted_last_risk)

#Consolidated data for abortion
aborted_complete <- aborted_inital_risk
colnames(aborted_complete)[which(colnames(aborted_complete) == "No_of_records")] <- "First_Reg_Records"

aborted_complete <- merge(aborted_complete, aborted_last_risk, by = "Risk_Status", all.x = TRUE)
colnames(aborted_complete)[which(colnames(aborted_complete) == "No_of_records")] <- "Final_Risk_Records"

print(aborted_complete)

#Initial and Final Risk Status of each Aborted pw profile
aborted_pw_status <- aborted_cases %>% select(pw_profile_id, risk_status, pw_case_flag_risk_status)
colnames(aborted_pw_status)[which(colnames(aborted_pw_status) == "risk_status")] <- "Initial_Risk_Status"
colnames(aborted_pw_status)[which(colnames(aborted_pw_status) == "pw_case_flag_risk_status")] <- "Final_Risk_Status"

#All combinations of Initial and Final Risk for aborted cases
agg_aborted_status <- aborted_pw_status %>%
  group_by(Initial_Risk_Status, Final_Risk_Status) %>%
  summarise(No_of_Records = n())

agg_aborted_status <- as.data.frame(agg_aborted_status)

print(agg_aborted_status)

#Write out the initial and final statuses to a file
write.csv(aborted_pw_status, "Aborted_cases.csv", row.names = FALSE)

#------------------------------Adverse Delivered cases---------------------

#filter by pregnancy outcome
adverse_delivered_cases <- adverse_cases_complete %>% filter(pw_case_close_preg_outcome == 1)

length(unique(adverse_delivered_cases$pw_profile_id))
#There are 226 adverse delivered cases

#Initial risk status of adverse delivered cases
agg_adv_delivered_first_reg <- adverse_delivered_cases %>% group_by(pw_case_close_delivery_outcome, risk_status) %>%
                               summarise(N = n())

gg <- ggplot(agg_adv_delivered_first_reg, aes(x = risk_status, y = N, fill = risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  facet_wrap(~ pw_case_close_delivery_outcome) +
  xlab("Risk Status") + ylab("Number of records") +
  ggtitle(("Adverse Delivered cases break up by Risk at First Registration"))

print(gg)

#Print the data
adv_delivered_inital_risk = data.frame(Delivery_Outcome =  agg_adv_delivered_first_reg$pw_case_close_delivery_outcome,
                                       Risk_Status = agg_adv_delivered_first_reg$risk_status,
                                       No_of_records =  agg_adv_delivered_first_reg$N)
print(adv_delivered_inital_risk)

#Count the number of various risk cases at last risk status
agg_adv_delivered_last_risk <- adverse_delivered_cases %>% group_by(pw_case_close_delivery_outcome, pw_case_flag_risk_status) %>%
                               summarise(N = n()) 

gg <- ggplot(agg_adv_delivered_last_risk, aes(x = pw_case_flag_risk_status, y = N, fill = pw_case_flag_risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  facet_wrap(~ pw_case_close_delivery_outcome) +
  xlab("Last Risk Status") + ylab("Number of records") +
  ggtitle(("Adverse Delivered cases break up by Last Risk Status"))

print(gg)

#Print the data
adv_delivered_last_risk = data.frame(Delivery_Outcome = agg_adv_delivered_last_risk$pw_case_close_delivery_outcome,
                                     Risk_Status = agg_adv_delivered_last_risk$pw_case_flag_risk_status,
                                     No_of_records =  agg_adv_delivered_last_risk$N)
print(adv_delivered_last_risk)

#Consolidated data for adverse delivered
adv_delivered_complete <- adv_delivered_inital_risk
colnames(adv_delivered_complete)[which(colnames(adv_delivered_complete) == "No_of_records")] <- "First_Reg_Records"

adv_delivered_complete <- merge(adv_delivered_complete, adv_delivered_last_risk, by = c("Delivery_Outcome", "Risk_Status"), all.x = TRUE)
colnames(adv_delivered_complete)[which(colnames(adv_delivered_complete) == "No_of_records")] <- "Final_Risk_Records"

print(adv_delivered_complete)

#Initial and Final Risk Status of each Aborted pw profile
adv_delivered_pw_status <- adverse_delivered_cases %>% select(pw_profile_id, risk_status, pw_case_flag_risk_status)
colnames(adv_delivered_pw_status)[which(colnames(adv_delivered_pw_status) == "risk_status")] <- "Initial_Risk_Status"
colnames(adv_delivered_pw_status)[which(colnames(adv_delivered_pw_status) == "pw_case_flag_risk_status")] <- "Final_Risk_Status"

#All combinations of Initial and Final Risk for aborted cases
agg_adv_delivered_status <- adv_delivered_pw_status %>%
  group_by(Initial_Risk_Status, Final_Risk_Status) %>%
  summarise(No_of_Records = n())

agg_adv_delivered_status <- as.data.frame(agg_adv_delivered_status)

print(agg_adv_delivered_status)

#Write out the initial and final statuses to a file
write.csv(adv_delivered_pw_status, "Adverse_Delivered_cases.csv", row.names = FALSE)

```

length(unique(closed_cases$pw_profile_id))
#There are 11932 closed cases