---
title: "Delivered_cases2"
author: "Ankur Shrivastava"
date: "2 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r bl1, echo=FALSE}
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(ggforce)
library(sqldf)
library(tidyr)

anm_visit <- read.csv("anm_visit_detail.csv", stringsAsFactors = FALSE, header = TRUE,
                      na.strings=c("NULL","NULL "," NULL ","NA"," ","", "-1"))
str(anm_visit)
summary(anm_visit)

# The following variables represent categories and not character or integers.
# Hence they need to be converted to categories
categorical <- c("anm_visit_detail_breathlessness", "anm_visit_detail_urine",
                 "anm_visit_detail_abdomen_pain", "anm_visit_detail_edema",
                 "anm_visit_detail_body_edema", "anm_visit_detail_headache")

#Converting to categorical variables

anm_visit[, categorical] <- lapply(anm_visit[, categorical], as.factor)
str(anm_visit[, categorical])

#Following are date variables and should be changed to date
anm_visit$anm_visit_detail_followup_date <- ymd(anm_visit$anm_visit_detail_followup_date)

#Following are datetime variables and should be changed to datetime
datetimevars <- c("anm_visit_detail_form_start_time", "anm_visit_detail_form_fill_time",
                  "anm_visit_detail_receive_time")

anm_visit[, datetimevars] <- lapply(anm_visit[, datetimevars], ymd_hms)
str(anm_visit[, datetimevars])

#Following are numeric variables and should be changed to numeric
numvars <- c("anm_visit_detail_temp", "anm_visit_detail_gps_lat", "anm_visit_detail_gps_long")

anm_visit[, numvars] <- lapply(anm_visit[, numvars], as.numeric)
str(anm_visit[, numvars])

anm_visit$risk_status <- as.factor(anm_visit$risk_status)

levels(anm_visit$risk_status) <- c("Normal", "Risk", "High Risk")
```
```{r bl2, echo=TRUE}
pw_case_flag <- read.csv("pw_case_flag.csv", stringsAsFactors = FALSE, header = TRUE,
                          na.strings=c("NULL","NULL "," NULL ","NA"," ","", "-1"))

str(pw_case_flag)
summary(pw_case_flag)

#Following are date variables and should be changed to date
pw_case_flag$anm_visit_detail_followup_date <- ymd(pw_case_flag$anm_visit_detail_followup_date)
pw_case_flag$doc_visit_detail_followup_date <- ymd(pw_case_flag$doc_visit_detail_followup_date)

#Following are datetime variables and should be changed to datetime
datetimevars <- c("pw_case_flag_set_time", "doc_visit_detail_last_visit_date")

pw_case_flag[, datetimevars] <- lapply(pw_case_flag[, datetimevars], ymd_hms)
str(pw_case_flag[, datetimevars])

length(unique(pw_case_flag$pw_profile_id))
#There are 43783 unique pw ids 
```
```{r bl3,echo=TRUE}
#Get all closed cases from pw_case_flag
pw_close <- sqldf("select * from pw_case_flag where pw_case_flag_closed = 1")

length(unique(pw_close$pw_profile_id))
#There are 11932 closed cases

#anm first registration records
anm_first_reg <- sqldf("select * from anm_visit where first_record = 1")

#Get all details for closed cases
closed_first_reg <- pw_close %>% left_join(anm_first_reg, by = "pw_profile_id")
str(closed_first_reg)

closed_first_reg$pw_case_flag_risk_status <- as.factor(closed_first_reg$pw_case_flag_risk_status)

levels(closed_first_reg$pw_case_flag_risk_status) <- c("Normal", "Risk", "High Risk")

#count the number of various risk cases at first registration
agg_first_reg <- distinct(closed_first_reg) %>% group_by(risk_status) %>%
                     summarise(N = n())

gg <- ggplot(agg_first_reg, aes(x = risk_status, y = N, fill = risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  xlab("Risk Status") + ylab("Number of records") +
  ggtitle(("Delivered cases break up by Risk at First Registration"))

print(gg)

#Print the data
inital_risk = data.frame(Risk_Status = agg_first_reg$risk_status, No_of_records =  agg_first_reg$N)
print(inital_risk)

#Count the number of various risk cases at last risk status
agg_last_risk <- closed_first_reg %>% group_by(pw_case_flag_risk_status) %>%
                 summarise(N = n()) 

gg <- ggplot(agg_last_risk, aes(x = pw_case_flag_risk_status, y = N, fill = pw_case_flag_risk_status)) + 
  geom_bar(stat = "identity", show.legend = TRUE) +
  geom_text(stat = "identity", aes(label = N), position = position_dodge(0.9),vjust = -0.2) +
  xlab("Risk Status") + ylab("Number of records") +
  ggtitle(("Delivered cases break up by Last Risk Status"))

print(gg)

#Print the data
final_status <- data.frame(Risk_Status = agg_last_risk$pw_case_flag_risk_status, No_of_records =  agg_last_risk$N)
print(final_status)

#Consolidated data
complete <- inital_risk
colnames(complete)[which(colnames(complete) == "No_of_records")] <- "First_Reg_Records"

complete <- merge(complete, final_status, by = "Risk_Status", all.x = TRUE)
colnames(complete)[which(colnames(complete) == "No_of_records")] <- "Final_Risk_Records"

print(complete)

#Initial and Final Risk Status of each Delivered pw profile
delivered_pw_status <- closed_first_reg %>% select(pw_profile_id, risk_status, pw_case_flag_risk_status)
colnames(delivered_pw_status)[which(colnames(delivered_pw_status) == "risk_status")] <- "Initial_Risk_Status"
colnames(delivered_pw_status)[which(colnames(delivered_pw_status) == "pw_case_flag_risk_status")] <- "Final_Risk_Status"

#Write out the initial and final statuses to a file
write.csv(delivered_pw_status, "Delivered_cases2.csv", row.names = FALSE)
```